_target_: data.dataset_generators.augment.Augmentor
n: 3

transform : 
  _target_: torchvision.transforms.Compose
  transforms:
    - _target_: torchvision.transforms.v2.RandAugment
      num_ops: 4
      magnitude: 10
    - _target_: torchvision.transforms.v2.ColorJitter
      brightness: 0.3
      contrast: 0.3
      saturation: 0.3
      hue: 0.1
    - _target_: torchvision.transforms.v2.RandomHorizontalFlip
      p: 0.5
    
    