_target_: data.dataset_generators.augment.Augmentor
n: 4

transform : 
  _target_: torchvision.transforms.v2.Compose
  transforms:
    - _target_: torchvision.transforms.v2.RandomHorizontalFlip
      p: 0.5
    - _target_: torchvision.transforms.v2.ColorJitter
      brightness: 0.4
      contrast: 0.4
      saturation: 0.4
      hue: 0.05
    - _target_: torchvision.transforms.v2.RandomAdjustSharpness
      p: 0.2
      sharpness_factor: 0.5
    - _target_: torchvision.transforms.v2.RandomPosterize
      p: 0.2
      bits: 4
    - _target_: torchvision.transforms.v2.RandomSolarize
      p: 0.2
      threshold: 240
    - _target_: torchvision.transforms.v2.RandomEqualize
      p: 0.2
    - _target_: torchvision.transforms.v2.RandomAutocontrast
      p: 0.2
    
    
    