
defaults:
  - transform: simple
  - model: dinov2

_target_: data.dataset_filter.classifier.ClassifierFilter

batch_size: ${batch_size}
input_dir: ${input_dir}
output_dir: ${output_dir}
true_dir: ${data_dir}/val
treshold: 0.1
from_checkpoint: false
num_epochs: 30
model_path: ${root_dir}/checkpoints/${experiment_name}.pt