_target_: data.dataset_filter.resnet_classifier.Classifier

defaults:
  - transforms: simple
  - model: resnet

batch_size: ${batch_size}
input_dir: ${data_dir}/train/simple_prompts
output_dir: ${data_dir}/train/simple_prompts_filtered
true_dir: ${data_dir}/val
treshold: 0.1
from_checkpoint: false
num_epochs: 10
model_path: ${root_dir}/checkpoints/${experiment_name}.pt

num_images_per_label: 400