_target_: torchvision.transforms.Compose
transforms:
  - _target_: torchvision.transforms.RandomResizedCrop
    size: 280
    scale: [0.6, 1.0]
  - _target_: torchvision.transforms.RandomRotation
    degrees: 10
  - _target_: torchvision.transforms.ColorJitter
    brightness: 0.3
    contrast: 0.3
    saturation: 0.3
    hue: 0.1
  - _target_: torchvision.transforms.ToTensor
  - _target_: torchvision.transforms.Normalize
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]

#- _target_: torchvision.transforms.RandomResizedCrop
#    size: 224
#    scale: [0.6, 1.0]