_target_: data.dataset_generators.random.RandomPromptsDatasetGenerator
generator: ${image_generator}
batch_size: ${batch_size}
output_dir: ${data_dir}/train/ipadapt
num_images_per_label: 500
augmentor: null
repertoire: ${root_dir}/prompts