_target_: data.dataset_generators.random.RandomPromptsDatasetGenerator
generator: ${image_generator}
batch_size: ${batch_size}
output_dir: ${data_dir}/train/random_prompts_augmented
num_images_per_label: 1000
augmentor: ${augmentor}
repertoire: ${root_dir}/prompts