defaults:
  - train_transform: simple
  - test_transform: simple
  - _self_

name: simple_prompts
num_classes: 4
batch_size: 128
num_workers: 8
train_path: ${data_dir}/train/simple_prompts
real_images_val_path: ${data_dir}/blueval
test_path: ${data_dir}/test