defaults:
  - train_transform: simple
  - test_transform: simple

name: ${dataset_name}
num_classes: 37
batch_size: 128
num_workers: 8
train_path: ${data_dir}/train/${dataset_name}
real_images_val_path: ${data_dir}/val
test_path: ${data_dir}/test