defaults:
  - model: dinov2
  - dataset: standard
  - optim: adamw
  - loss_fn: cross_entropy
  - _self_

epochs: 10

dataset_name: simple_prompts

datamodule:
  _target_: data.datamodule.DataModule
  train_dataset_path: ${dataset.train_path}
  real_images_val_path: ${dataset.real_images_val_path}
  train_transform: ${dataset.train_transform}
  val_transform: ${dataset.test_transform}
  batch_size: ${dataset.batch_size}
  num_workers: ${dataset.num_workers}

data_dir: ${root_dir}/dataset
root_dir:  ${hydra:runtime.cwd}
checkpoint_path: ${root_dir}/checkpoints/submitted/1_divov2_simple_prompts_epoch_3.pt

experiment_name: ${model.name}_${dataset.name}_pour_corentin
hydra:
  run:
    dir: outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}/
  job:
    chdir: true